# =========================
# APPLICATIONS OPACITY
# =========================

# # windowrule = opacity 0.8, class:^(org.gnome.Nautilus)$
# # windowrule = opacity 0.9, class:^(gedit|org.gnome.TextEditor|mousepad)$
# windowrule = opacity 0.9, class:^(org.pulseaudio.pavucontrol)$
# windowrule = opacity 0.9, class:^(kitty)$
#
# windowrule = opacity 0.85, class:^(discord|vesktop|org.telegram.desktop)$
# windowrule = opacity 0.7, class:^(discord|vesktop|org.telegram.desktop)$
#
# windowrule = opacity 0.8, class:^(Spotify)$
# windowrule = opacity 0.6, class:^(Spotify)$
#
# windowrule = opacity 0.9, class:^(zen)$
# windowrule = opacity 0.7, class:^(zen)$

# =========================
# FLOATING APPS
# =========================

# windowrule = float, class:^(org.pulseaudio.pavucontrol)$
# windowrule = size 50% 60%, class:^(org.pulseaudio.pavucontrol)$
#
# windowrule = float, class:^(zen)$
# windowrule = float, class:^(kitty)$
#
# windowrule = size 900 506, class:^(mpv|vlc)$

# =========================
# SYSTEM RULES
# =========================

# windowrule = suppressevent maximize, class:.*
# windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# =========================
# POPUPS / DIALOGS
# =========================

# windowrule = float, title:^(Save As|Save a File|Pick Files)$
# windowrule = size 50% 60%, title:^(Save As|Save a File|Pick Files)$
# windowrule = center, title:^(Save As|Save a File|Pick Files)$

# windowrule = float, initialTitle:^(Open Files)$
# windowrule = size 70% 60%, initialTitle:^(Open Files)$

# =========================
# LAYERS (OK)
# =========================

# layerrule = blur, waybar
# layerrule = ignorealpha 0.5, waybar
#
# layerrule = blur, logout_dialog
#
# layerrule = blur, swaync-control-center
# layerrule = blur, swaync-notification-window
#
# layerrule = ignorezero, swaync-control-center
# layerrule = ignorezero, swaync-notification-window
#
# layerrule = ignorealpha 0.5, swaync-control-center
# layerrule = ignorealpha 0.5, swaync-notification-window
#
# layerrule = xray 0, swaync-control-center
# layerrule = xray 0, swaync-notification-window
